version: '3.8'

services:
  react:
    image: react_app
    build:
      context: ./react
    container_name: react_app_container
    ports:
      - "3333:3333"
    volumes:
      - ./react:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  svelte:
    image: svelte_app
    build:
      context: ./svelte
    ports:
      - "4444:4444"
    volumes:
      - ./svelte:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  vue:
    image: vue_app
    build:
      context: ./vue
    ports:
      - "8888:8888"
    volumes:
      - ./vue:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  express:
    image: express_app
    build:
      context: ./vue
    ports:
      - "5555:5555"
    volumes:
      - ./express:/app
      - /app/node_modules
    stdin_open: true
    tty: true
#
#  nest:
#    image: nest_app
#    build:
#      context: ./nest
#    ports:
#      - "7777:3000"
#
#  golang:
#    image: golang_app
#    build:
#      context: ./golang
#    ports:
#      - "8081:8081"
#
#  mongo:
#    image: mongo:latest
#    volumes:
#      - mongo_data:/data/db
#    ports:
#      - "27017:27017"
#
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"

#volumes:
#  mongo_data:
#    driver: local
