const EMPTY_STRING = '';
const MILLISECONDS_IN_SECOND =  1000;
const MILLISECONDS_IN_MINUTE =  1000 * 60;
const MILLISECONDS_IN_HOUR =  1000 * 60 * 60;
const MILLISECONDS_IN_DAY =  1000 * 60 * 60 * 24;
const LOCAL_STORAGE_THEME_KEY = 'theme';

export { EMPTY_STRING, MILLISECONDS_IN_SECOND, MILLISECONDS_IN_MINUTE, MILLISECONDS_IN_HOUR, MILLISECONDS_IN_DAY, LOCAL_STORAGE_THEME_KEY };
